name: CI Pipeline Advance

on:
  push:
    branches:
      - main

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn==1.5.2 matplotlib mlflow==2.19.0

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Upload Artifacts ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/

      - name: Login ke Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image menggunakan MLflow
        run: |
          cd MLProject
          RUN_ID=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
          
          # Tambahkan parameter --python-version 3.10 untuk sinkronisasi dengan pip
          mlflow models build-docker \
            -m "mlruns/0/$RUN_ID/artifacts/random_forest_model" \
            -n ${{ secrets.DOCKERHUB_USERNAME }}/heart-model:latest \
            --env-manager=virtualenv \
            --python-version 3.10